#
# SignService configuration
#

server:
  servlet:
    context-path: /    
  ssl:
    enabled: true
    key-store: classpath:snakeoil.jks
    key-store-type: JKS
    key-alias: localhost
    key-store-password: secret
    key-password: secret

#
# Management
#
management:
  server:
    port: 8444
    ssl:
      enabled: true
      key-store: classpath:snakeoil.jks
      key-store-type: JKS
      key-alias: localhost
      key-store-password: secret
      key-password: secret
      
  health:
    ping:
      enabled: true
    diskspace:
      enabled: true    
  auditevents:
    enabled: true
    
  endpoint:
    auditevents:
      enabled: true
    health:
      show-details: ALWAYS      
  endpoints:
    web:
      exposure:
        include: health,info,auditevents

signservice:
  domain: localhost
  base-url: https://${signservice.domain}:${server.port}
  default-sign-service-id: https://sandbox.swedenconnect.se/signservice
  system-audit:
    actuator:
      name: "SignService System Audit Logger"
      principal: "SignService"  
  default-credential:
    props:      
      name: SignService
      resource: classpath:signservice.jks
      alias: signservice
      type: JKS
      password: secret
      key-password: secret
  validation-config:
    allowed-clock-skew: PT30S
    max-message-age: PT3M
  common-beans:
    protocol:
      bean-name: signservice.DssProtocolHandler
      dss:
        include-assertion: true
        include-request-message: false
    sign:
      bean-name: signservice.DefaultSignatureHandler
      default-handler:
        name: DefaultSignatureHandler
        tbs-processors:
        - type: xml
          strict-processing: false
          include-issuer-serial: true
        - type: pdf
    key-provider:
      bean-name: signservice.DefaultKeyProvider
      security-provider: BC
    saml:
      metadata-provider:
        bean-name: signservice.SamlMetadataProvider
        url: https://mds.swamid.se/md/swamid-idp.xml
        backup-file: ${SIGNSERVICE_HOME}/metadata-cache/swamid-metadata.xml
        validation-certificate: classpath:swamid/md-signer2.crt
  default-handler-config:
    authn:
      saml:
        saml-type: sweden-connect
        entity-id: ${signservice.default-sign-service-id}
        sp-paths:
          base-url: ${signservice.base-url}
        metadata-provider-ref: signservice.SamlMetadataProvider
        signature-credential:
          props:
            name: SignService SAML Signing
            resource: classpath:sandbox/saml-sp.jks
            alias: sign
            type: JKS
            password: secret
            key-password: secret
        decryption-credential:
          props:            
            name: SignService SAML Decryption
            resource: classpath:sandbox/saml-sp.jks
            alias: encrypt
            type: JKS
            password: secret
            key-password: secret
        sign-authn-requests: true
        require-encrypted-assertions: true
        require-signed-assertions: true
        message-replay-checker-ref: signservice.MessageReplayChecker
        metadata:
          entity-categories:
          - http://refeds.org/category/research-and-scholarship
          - http://www.geant.net/uri/dataprotection-code-of-conduct/v1
          - https://refeds.org/category/code-of-conduct/v2
          requested-attributes:
          - name: urn:oid:2.16.840.1.113730.3.1.241
            required: true
          - name: urn:oid:1.3.6.1.4.1.5923.1.1.1.11
            required: true
          - name: urn:oid:1.3.6.1.4.1.5923.1.1.1.6
            required: true
          - name: urn:oid:2.5.4.42
            required: true
          - name: urn:oid:0.9.2342.19200300.100.1.3
            required: true
          - name: urn:oid:2.5.4.4
            required: true
          service-names:
          - "sv-SUNET eduSIGN - tjänst för e-signaturer"
          - "en-SUNET eduSIGN Service"
          ui-info:
            display-names:
            - "sv-SUNET underskriftstjänst"
            - "en-SUNET signing service"
            descriptions:
            - "sv-Underskriftstjänst för eduSign"
            - "en-eduSign Signing Service"
            logos:
            - path: /images/eduSign.png
              height: 50
              width: 201
          organization:
            names:
            - "sv-Vetenskapsrådet"
            - "en-The Swedish Research Council"
            display-names:
            - "sv-Sunet"
            - "en-Sunet"
            urls:
            - "en-https://www.sunet.se"
            - "sv-https://www.sunet.se"
          contact-persons:
            support:
              given-name: SUNET
              surname: NOC
              email-address: noc@sunet.se
              telephone-number: +46 90-20 59 100
            technical:
              given-name: SUNET
              surname: NOC
              email-address: noc@sunet.se
              telephone-number: +46 8 20 78 60
            administrative:
              given-name: SUNET
              surname: NOC
              email-address: noc@sunet.se              

#
# Logging
#
logging:
  level:
    se:
      swedenconnect:
        security: INFO
        signservice: INFO
#  file:
#    path: app/target/logs


#logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
