#
# Configuration for a SignService running locally and supporting one client that is
# the Signature Service Test Application (https://sig.sandbox.swedenconnect.se/testsp/login).
#

server:
  port: 8443
  servlet:
    context-path: /edusign-signservice  
        
signservice-config:
  client-config-dir: classpath:clients
      
signservice:
  domain: local.dev.idsec.se
  base-url: https://${signservice.domain}:${server.port}${server.servlet.context-path}
  default-sign-service-id: https://local.dev.idsec.se/signservice
  common-beans:
    cert:
      bean-name: signservice.BuiltInCa
      built-in-ca:
        base-url: ${signservice.base-url}
        ca-credential:
          props:
            resource: classpath:ca/test-ca.jks
            type: JKS
            password: secret
            alias: test-ca
            key-password: secret
        ca-signing-algorithm: http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256
        ca-supported-certificate-types:
        - PKC
        key-provider-ref: signservice.DefaultKeyProvider
        cert-validity: P365D
        crl-validity: P2D
        crl-dp-path: /signca/signca.crl
        crl-file-location: ${SIGNSERVICE_HOME}/signca/signca.crl
        default-value-policy-checker:
          default-reply: false
          rules:
          - attribute-type: rdn
            ref: "2.5.4.6"
            allowed-values:
            - SE
  engines:
  - name: "upload-and-sign-localdev"
    sign-service-id: https://sig.idsec.se/edusign-signservice
    processing-paths:
    - /sign/uas/signrequest
    client:
      client-id: https://sig.idsec.se/sigserv-v2-sp
      trusted-certificates:
      - ${signservice-config.client-config-dir}/uas/uas.crt
    protocol:
      external:
        bean-name: signservice.DssProtocolHandler
    authn:
      saml:      
        default-config-ref: authn.saml
        entity-id: https://sig.idsec.se/uas
        sp-paths:
          metadata-publishing-path: /sign/uas/saml/metadata
          assertion-consumer-path: /sign/uas/saml/sso
        preferred-binding: POST
        metadata:
          template: ${signservice-config.client-config-dir}/uas/idsec-localdev-template.xml
    sign:
      external:
        bean-name: signservice.DefaultSignatureHandler    
    cert:
      external:
        bean-name: signservice.BuiltInCa
    audit:
      file:
        name: "uas-localhost-audit"
        file-name: ${SIGNSERVICE_HOME}/uas/audit.log


#
# Logging
#
logging:
  level:
    se:
      swedenconnect:
        security: DEBUG
        signservice: DEBUG
