#
# SignService configuration
#

server:
  servlet:
    context-path: /    
  ssl:
    enabled: true
    key-store: classpath:snakeoil.jks
    key-store-type: JKS
    key-alias: localhost
    key-store-password: secret
    key-password: secret

#
# Management
#
management:
  server:
    port: 8444
    ssl:
      enabled: true
      key-store: classpath:snakeoil.jks
      key-store-type: JKS
      key-alias: localdev
      key-store-password: secret
      key-password: secret
      
  health:
    ping:
      enabled: true
    diskspace:
      enabled: true    
  auditevents:
    enabled: true
    
  endpoint:
    auditevents:
      enabled: true
    health:
      show-details: ALWAYS      
  endpoints:
    web:
      exposure:
        include: health,info,auditevents

signservice:
  domain: local.dev.idsec.se
  base-url: https://${signservice.domain}:${server.port}
  default-sign-service-id: https://${signservice.domain}/edusign-signservice
  system-audit:
    actuator:
      name: "SignService System Audit Logger"
      principal: "SignService"  
  default-credential:
    props:      
      name: SignService
      resource: classpath:signservice.jks
      alias: signservice
      type: JKS
      password: secret
      key-password: secret
  validation-config:
    allowed-clock-skew: PT30S
    max-message-age: PT3M
  common-beans:
    protocol:
      bean-name: signservice.DssProtocolHandler
      dss:
        include-assertion: true
        include-request-message: false
    sign:
      bean-name: signservice.DefaultSignatureHandler
      default-handler:
        name: DefaultSignatureHandler
        tbs-processors:
        - type: xml
          strict-processing: false
          include-issuer-serial: true
        - type: pdf
    key-provider:
      bean-name: signservice.DefaultKeyProvider
      security-provider: BC
    saml:
      metadata-provider:
        bean-name: signservice.SamlMetadataProvider
        url: https://mds.swamid.se/md/swamid-idp.xml
        backup-location: ${SIGNSERVICE_HOME}/metadata-cache/swamid-metadata.xml
        validation-certificate: classpath:swamid/md-signer2.crt
  default-handler-config:
    authn:
      saml:
        factory-class: se.sunet.edusign.saml.SwamidSamlAuthenticationHandlerFactory
        saml-type: swamid
        entity-id: ${signservice.default-sign-service-id}
        sp-paths:
          base-url: ${signservice.base-url}
        metadata-provider-ref: signservice.SamlMetadataProvider
        signature-credential:
          props:
            name: SignService SAML Signing
            resource: classpath:sandbox/saml-sp.jks
            alias: sign
            type: JKS
            password: secret
            key-password: secret
        decryption-credential:
          props:            
            name: SignService SAML Decryption
            resource: classpath:sandbox/saml-sp.jks
            alias: encrypt
            type: JKS
            password: secret
            key-password: secret
        sign-authn-requests: true
        require-encrypted-assertions: false
        require-signed-assertions: false
        message-replay-checker-ref: signservice.MessageReplayChecker
#        metadata:
#          template: classpath:swamid/sp-template.xml

#
# Logging
#
logging:
  level:
    se:
      swedenconnect:
        security: INFO
        signservice: INFO
#  file:
#    path: app/target/logs


#logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
